# Site settings
title: Mauricio Urraco
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 适用于RA3的地图测试
user_description: 适用于RA3的地图<b>crypto-world</b>于2018年的黑历史 <a href="https://send.firefox.com/download/c0f01fdd317d1ca9/#8axvtA-btEEOQ0qciGieRg" target="_blank">https://send.firefox.com/download/c0f01fdd317d1ca9/#8axvtA-btEEOQ0qciGieRg</a>
user_title: 地图测试
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
